"""empty message

Revision ID: 2fe166270eba
Revises: afc2d9756538
Create Date: 2023-05-24 21:11:02.307001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2fe166270eba"
down_revision = "afc2d9756538"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "convex_cumulative_revenue",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("totalCrvRevenueToLpProviders", sa.Float(), nullable=True),
        sa.Column("totalCvxRevenueToLpProviders", sa.Float(), nullable=True),
        sa.Column("totalFxsRevenueToLpProviders", sa.Float(), nullable=True),
        sa.Column("totalCrvRevenueToCvxCrvStakers", sa.Float(), nullable=True),
        sa.Column("totalCvxRevenueToCvxCrvStakers", sa.Float(), nullable=True),
        sa.Column(
            "totalThreeCrvRevenueToCvxCrvStakers", sa.Float(), nullable=True
        ),
        sa.Column("totalFxsRevenueToCvxFxsStakers", sa.Float(), nullable=True),
        sa.Column("totalCrvRevenueToCvxStakers", sa.Float(), nullable=True),
        sa.Column("totalFxsRevenueToCvxStakers", sa.Float(), nullable=True),
        sa.Column("totalCrvRevenueToCallers", sa.Float(), nullable=True),
        sa.Column("totalFxsRevenueToCallers", sa.Float(), nullable=True),
        sa.Column("totalCrvRevenueToPlatform", sa.Float(), nullable=True),
        sa.Column("totalFxsRevenueToPlatform", sa.Float(), nullable=True),
        sa.Column("totalCrvRevenue", sa.Float(), nullable=True),
        sa.Column("totalFxsRevenue", sa.Float(), nullable=True),
        sa.Column("totalOtherRevenue", sa.Float(), nullable=True),
        sa.Column("totalBribeRevenue", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "convex_pool_snapshot",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("poolid", sa.String(), nullable=True),
        sa.Column("poolName", sa.String(), nullable=True),
        sa.Column("swap", sa.String(), nullable=True),
        sa.Column("withdrawalCount", sa.Integer(), nullable=True),
        sa.Column("withdrawalVolume", sa.Integer(), nullable=True),
        sa.Column("withdrawalValue", sa.Float(), nullable=True),
        sa.Column("depositCount", sa.Integer(), nullable=True),
        sa.Column("depositVolume", sa.Integer(), nullable=True),
        sa.Column("depositValue", sa.Float(), nullable=True),
        sa.Column("lpTokenBalance", sa.Integer(), nullable=True),
        sa.Column("lpTokenVirtualPrice", sa.Float(), nullable=True),
        sa.Column("lpTokenUSDPrice", sa.Float(), nullable=True),
        sa.Column("tvl", sa.Float(), nullable=True),
        sa.Column("curveTvlRatio", sa.Float(), nullable=True),
        sa.Column("baseApr", sa.Float(), nullable=True),
        sa.Column("crvApr", sa.Float(), nullable=True),
        sa.Column("cvxApr", sa.Float(), nullable=True),
        sa.Column("extraRewardsApr", sa.Float(), nullable=True),
        sa.Column("timestamp", sa.Integer(), nullable=True),
        sa.Column("block", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "convex_revenue_snapshot",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("crvRevenueToLpProvidersAmount", sa.Float(), nullable=True),
        sa.Column("cvxRevenueToLpProvidersAmount", sa.Float(), nullable=True),
        sa.Column(
            "crvRevenueToCvxCrvStakersAmount", sa.Float(), nullable=True
        ),
        sa.Column(
            "cvxRevenueToCvxCrvStakersAmount", sa.Float(), nullable=True
        ),
        sa.Column(
            "threeCrvRevenueToCvxCrvStakersAmount", sa.Float(), nullable=True
        ),
        sa.Column("crvRevenueToCvxStakersAmount", sa.Float(), nullable=True),
        sa.Column("crvRevenueToCallersAmount", sa.Float(), nullable=True),
        sa.Column("crvRevenueToPlatformAmount", sa.Float(), nullable=True),
        sa.Column("totalCrvRevenue", sa.Float(), nullable=True),
        sa.Column("fxsRevenueToCvxStakersAmount", sa.Float(), nullable=True),
        sa.Column(
            "fxsRevenueToCvxFxsStakersAmount", sa.Float(), nullable=True
        ),
        sa.Column("fxsRevenueToLpProvidersAmount", sa.Float(), nullable=True),
        sa.Column("fxsRevenueToCallersAmount", sa.Float(), nullable=True),
        sa.Column("fxsRevenueToPlatformAmount", sa.Float(), nullable=True),
        sa.Column("totalFxsRevenue", sa.Float(), nullable=True),
        sa.Column("otherRevenue", sa.Float(), nullable=True),
        sa.Column("bribeRevenue", sa.Float(), nullable=True),
        sa.Column("cvxPrice", sa.Float(), nullable=True),
        sa.Column("fxsPrice", sa.Float(), nullable=True),
        sa.Column("crvPrice", sa.Float(), nullable=True),
        sa.Column("timestamp", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("convex_revenue_snapshot")
    op.drop_table("convex_pool_snapshot")
    op.drop_table("convex_cumulative_revenue")
    # ### end Alembic commands ###
