"""Store active price band

Revision ID: d7163f9e81dd
Revises: 175a19551978
Create Date: 2023-08-31 22:35:30.945842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d7163f9e81dd"
down_revision = "175a19551978"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_state_snapshots", schema=None) as batch_op:
        batch_op.add_column(sa.Column("activeBand", sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_state_snapshots", schema=None) as batch_op:
        batch_op.drop_column("activeBand")

    # ### end Alembic commands ###
