"""empty message

Revision ID: f0e2060cec74
Revises: 3ccf67e9cf88
Create Date: 2023-05-25 00:18:57.283320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f0e2060cec74"
down_revision = "3ccf67e9cf88"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("convex_pool_snapshot", schema=None) as batch_op:
        batch_op.alter_column(
            "depositVolume",
            existing_type=sa.INTEGER(),
            type_=sa.Numeric(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("convex_pool_snapshot", schema=None) as batch_op:
        batch_op.alter_column(
            "depositVolume",
            existing_type=sa.Numeric(),
            type_=sa.INTEGER(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
