"""Store decoded scripts

Revision ID: 772eb03e01b2
Revises: 87146a6f3b61
Create Date: 2023-08-22 12:03:35.559465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "772eb03e01b2"
down_revision = "87146a6f3b61"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "curve_dao_proposal_scripts",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("script", sa.String(), nullable=True),
        sa.Column("decodedScript", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("curve_dao_proposal_scripts")
    # ### end Alembic commands ###
