"""Store couch info in DB

Revision ID: 40c4202550ee
Revises: 741041620555
Create Date: 2023-06-08 22:04:52.798765

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "40c4202550ee"
down_revision = "741041620555"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "couch_info",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("poolId", sa.String(), nullable=True),
        sa.Column("balance", postgresql.ARRAY(sa.Float()), nullable=True),
        sa.Column("value", postgresql.ARRAY(sa.Float()), nullable=True),
        sa.Column("totalUSD", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["poolId"],
            ["curve_pool.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("couch_info")
    # ### end Alembic commands ###
