"""Add an entity to store metadata from IPFS

Revision ID: 992413e7ca33
Revises: 9a883e29f4fd
Create Date: 2023-11-22 07:17:35.252186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "992413e7ca33"
down_revision = "9a883e29f4fd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "curve_dao_proposal_metadata",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("ipfs_metadata", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("curve_dao_proposal_metadata")
    # ### end Alembic commands ###
