"""Store available stable to borrow

Revision ID: 36b5aef074dd
Revises: f1c6f0de5213
Create Date: 2023-09-06 21:47:26.208371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "36b5aef074dd"
down_revision = "f1c6f0de5213"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("snapshot", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("available", sa.Numeric(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("snapshot", schema=None) as batch_op:
        batch_op.drop_column("available")

    # ### end Alembic commands ###
