"""Store stablecoin balance

Revision ID: ed182c4be41d
Revises: 5e9011919bbf
Create Date: 2023-09-01 12:53:16.393393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ed182c4be41d"
down_revision = "5e9011919bbf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_state_snapshots", schema=None) as batch_op:
        batch_op.add_column(sa.Column("stablecoin", sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_state_snapshots", schema=None) as batch_op:
        batch_op.drop_column("stablecoin")

    # ### end Alembic commands ###
