"""Change int to numeric for bigint

Revision ID: f2768134004f
Revises: a66e9d641eed
Create Date: 2023-05-26 16:46:27.455467

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f2768134004f"
down_revision = "a66e9d641eed"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("curve_pool_snapshot", schema=None) as batch_op:
        batch_op.alter_column(
            "reserves",
            existing_type=postgresql.ARRAY(sa.INTEGER()),
            type_=postgresql.ARRAY(sa.Numeric()),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "normalizedReserves",
            existing_type=postgresql.ARRAY(sa.INTEGER()),
            type_=postgresql.ARRAY(sa.Numeric()),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("curve_pool_snapshot", schema=None) as batch_op:
        batch_op.alter_column(
            "normalizedReserves",
            existing_type=postgresql.ARRAY(sa.Numeric()),
            type_=postgresql.ARRAY(sa.INTEGER()),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "reserves",
            existing_type=postgresql.ARRAY(sa.Numeric()),
            type_=postgresql.ARRAY(sa.INTEGER()),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
