"""Rename marketId to market

Revision ID: 5a1802b52745
Revises: ad51e6ed4f1f
Create Date: 2023-06-07 22:23:43.273956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5a1802b52745"
down_revision = "ad51e6ed4f1f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("amm", schema=None) as batch_op:
        batch_op.add_column(sa.Column("market", sa.String(), nullable=True))
        batch_op.drop_column("marketId")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("amm", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "marketId", sa.VARCHAR(), autoincrement=False, nullable=True
            )
        )
        batch_op.drop_column("market")

    # ### end Alembic commands ###
