"""empty message

Revision ID: 3ccf67e9cf88
Revises: c4b9f7a34724
Create Date: 2023-05-24 23:38:50.591088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3ccf67e9cf88"
down_revision = "c4b9f7a34724"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("convex_pool_snapshot", schema=None) as batch_op:
        batch_op.alter_column(
            "withdrawalCount",
            existing_type=sa.BIGINT(),
            type_=sa.Numeric(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "withdrawalVolume",
            existing_type=sa.BIGINT(),
            type_=sa.Numeric(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "lpTokenBalance",
            existing_type=sa.BIGINT(),
            type_=sa.Numeric(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("convex_pool_snapshot", schema=None) as batch_op:
        batch_op.alter_column(
            "lpTokenBalance",
            existing_type=sa.Numeric(),
            type_=sa.BIGINT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "withdrawalVolume",
            existing_type=sa.Numeric(),
            type_=sa.BIGINT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "withdrawalCount",
            existing_type=sa.Numeric(),
            type_=sa.BIGINT(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
