"""Store asset type and pool type

Revision ID: b68dfb7815be
Revises: 43526866a315
Create Date: 2023-05-27 18:40:09.941325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b68dfb7815be"
down_revision = "43526866a315"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("curve_pool", schema=None) as batch_op:
        batch_op.add_column(sa.Column("poolType", sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column("assetType", sa.Integer(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("curve_pool", schema=None) as batch_op:
        batch_op.drop_column("assetType")
        batch_op.drop_column("poolType")

    # ### end Alembic commands ###
