"""Add use and index to user states

Revision ID: f36c8622157c
Revises: a4f1dc3008ac
Create Date: 2023-06-09 23:36:38.711608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f36c8622157c"
down_revision = "a4f1dc3008ac"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_states", schema=None) as batch_op:
        batch_op.add_column(sa.Column("index", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("user", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_states", schema=None) as batch_op:
        batch_op.drop_column("user")
        batch_op.drop_column("index")

    # ### end Alembic commands ###
