"""Store limit bands on15m snapshot

Revision ID: a37c6eace0ed
Revises: 77ee3959df60
Create Date: 2023-09-03 10:25:16.205401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a37c6eace0ed"
down_revision = "77ee3959df60"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_states", schema=None) as batch_op:
        batch_op.add_column(sa.Column("N1", sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column("N2", sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column("softLiq", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_states", schema=None) as batch_op:
        batch_op.drop_column("softLiq")
        batch_op.drop_column("N2")
        batch_op.drop_column("N1")

    # ### end Alembic commands ###
