"""Store debt ceiling and mints/burns

Revision ID: f1c6f0de5213
Revises: a37c6eace0ed
Create Date: 2023-09-06 20:41:23.936068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f1c6f0de5213"
down_revision = "a37c6eace0ed"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "burns",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column("blockNumber", sa.Integer(), nullable=True),
        sa.Column("blockTimestamp", sa.Integer(), nullable=True),
        sa.Column("transactionHash", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "debt_ceilings",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column("blockNumber", sa.Integer(), nullable=True),
        sa.Column("blockTimestamp", sa.Integer(), nullable=True),
        sa.Column("transactionHash", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "mints",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column("blockNumber", sa.Integer(), nullable=True),
        sa.Column("blockTimestamp", sa.Integer(), nullable=True),
        sa.Column("transactionHash", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("mints")
    op.drop_table("debt_ceilings")
    op.drop_table("burns")
    # ### end Alembic commands ###
