"""Store historical debt levels

Revision ID: 87146a6f3b61
Revises: 5b748ccc0026
Create Date: 2023-08-08 16:19:05.646215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "87146a6f3b61"
down_revision = "5b748ccc0026"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "historical_keeper_debt",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("keeperId", sa.String(), nullable=True),
        sa.Column("debt", sa.Numeric(), nullable=True),
        sa.Column("timestamp", sa.Integer(), nullable=True),
        sa.Column("blockNumber", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["keeperId"],
            ["pegKeeper.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("historical_keeper_debt")
    # ### end Alembic commands ###
