"""Store xcpProfit and xcpProfitA in snapshots

Revision ID: de9923d4aa43
Revises: 5a1802b52745
Create Date: 2023-06-08 11:31:27.966318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "de9923d4aa43"
down_revision = "5a1802b52745"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("curve_pool_snapshot", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("xcpProfit", sa.Numeric(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("xcpProfitA", sa.Numeric(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("curve_pool_snapshot", schema=None) as batch_op:
        batch_op.drop_column("xcpProfitA")
        batch_op.drop_column("xcpProfit")

    # ### end Alembic commands ###
