"""Store liquidation discounts

Revision ID: 9a883e29f4fd
Revises: 36b5aef074dd
Create Date: 2023-09-07 11:37:25.989301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9a883e29f4fd"
down_revision = "36b5aef074dd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_liquidation_discount",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user", sa.String(), nullable=True),
        sa.Column("market_id", sa.String(), nullable=True),
        sa.Column("discount", sa.Float(), nullable=True),
        sa.Column("block", sa.Integer(), nullable=True),
        sa.Column("timestamp", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["market_id"],
            ["market.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table(
        "user_liquidation_discount", schema=None
    ) as batch_op:
        batch_op.create_index(
            "idx_user_liquidation_discount__user__market_id__block",
            ["user", "market_id", "block"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "user_liquidation_discount", schema=None
    ) as batch_op:
        batch_op.drop_index(
            "idx_user_liquidation_discount__user__market_id__block"
        )

    op.drop_table("user_liquidation_discount")
    # ### end Alembic commands ###
