"""Tie pegkeeper to pool

Revision ID: c26e332c1ae4
Revises: 04d43125b241
Create Date: 2023-06-15 09:53:05.158749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c26e332c1ae4"
down_revision = "04d43125b241"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pegKeeper", schema=None) as batch_op:
        batch_op.add_column(sa.Column("pool", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pegKeeper", schema=None) as batch_op:
        batch_op.drop_column("pool")

    # ### end Alembic commands ###
