"""Store oracle price & usd value with liquidatoins

Revision ID: 77ee3959df60
Revises: ed182c4be41d
Create Date: 2023-09-01 13:53:34.819306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "77ee3959df60"
down_revision = "ed182c4be41d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("liquidation", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("collateralReceivedUSD", sa.Numeric(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("oraclePrice", sa.Numeric(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("liquidation", schema=None) as batch_op:
        batch_op.drop_column("oraclePrice")
        batch_op.drop_column("collateralReceivedUSD")

    # ### end Alembic commands ###
