"""add chain column for crvusd markets

Revision ID: 5b748ccc0026
Revises: bded092cff08
Create Date: 2023-07-27 15:18:04.336904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5b748ccc0026"
down_revision = "bded092cff08"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("market", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("chain", sa.String(), server_default="mainnet")
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("market", schema=None) as batch_op:
        batch_op.drop_column("chain")

    # ### end Alembic commands ###
