"""empty message

Revision ID: afc2d9756538
Revises:
Create Date: 2023-05-23 17:40:46.365285

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "afc2d9756538"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "convex_pool",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("token", sa.String(), nullable=True),
        sa.Column("lpToken", sa.String(), nullable=True),
        sa.Column("swap", sa.String(), nullable=True),
        sa.Column("gauge", sa.String(), nullable=True),
        sa.Column("crvRewardsPool", sa.String(), nullable=True),
        sa.Column("isV2", sa.Boolean(), nullable=True),
        sa.Column("creationDate", sa.Integer(), nullable=True),
        sa.Column("creationBlock", sa.Integer(), nullable=True),
        sa.Column("tvl", sa.Float(), nullable=True),
        sa.Column("curveTvlRatio", sa.Float(), nullable=True),
        sa.Column("baseApr", sa.Float(), nullable=True),
        sa.Column("crvApr", sa.Float(), nullable=True),
        sa.Column("cvxApr", sa.Float(), nullable=True),
        sa.Column("extraRewardsApr", sa.Float(), nullable=True),
        sa.Column(
            "extraRewards", postgresql.ARRAY(sa.String()), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("convex_pool")
    # ### end Alembic commands ###
