"""Add fee tracking to DB models

Revision ID: 04d43125b241
Revises: f36c8622157c
Create Date: 2023-06-12 22:37:01.438034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "04d43125b241"
down_revision = "f36c8622157c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collectedFees",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("marketId", sa.String(), nullable=True),
        sa.Column("borrowingFees", sa.Float(), nullable=True),
        sa.Column("ammCollateralFees", sa.Float(), nullable=True),
        sa.Column("ammCollateralFeesUsd", sa.Float(), nullable=True),
        sa.Column("ammBorrowingFees", sa.Float(), nullable=True),
        sa.Column("blockNumber", sa.Integer(), nullable=True),
        sa.Column("blockTimestamp", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["marketId"],
            ["market.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("snapshot", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("adminBorrowingFees", sa.Numeric(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("snapshot", schema=None) as batch_op:
        batch_op.drop_column("adminBorrowingFees")

    op.drop_table("collectedFees")
    # ### end Alembic commands ###
