"""Add period to crvusd market volume snapshots

Revision ID: c81e95c5a297
Revises: 40c4202550ee
Create Date: 2023-06-09 16:47:16.746962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c81e95c5a297"
down_revision = "40c4202550ee"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("volumeSnapshot", schema=None) as batch_op:
        batch_op.add_column(sa.Column("period", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("volumeSnapshot", schema=None) as batch_op:
        batch_op.drop_column("period")

    # ### end Alembic commands ###
