"""Store price oracle

Revision ID: 5e9011919bbf
Revises: d7163f9e81dd
Create Date: 2023-09-01 11:31:05.457055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5e9011919bbf"
down_revision = "d7163f9e81dd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_state_snapshots", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("oraclePrice", sa.Float(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_state_snapshots", schema=None) as batch_op:
        batch_op.drop_column("oraclePrice")

    # ### end Alembic commands ###
