"""Add indexes

Revision ID: c96dc1fbed05
Revises: 992413e7ca33
Create Date: 2024-04-14 20:54:21.596794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c96dc1fbed05'
down_revision = '992413e7ca33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snapshot', schema=None) as batch_op:
        batch_op.create_index('idx_snapshot__llamma__market_id__timestamp', ['llammaId', 'marketId', 'timestamp'], unique=False)

    with op.batch_alter_table('user_state_snapshots', schema=None) as batch_op:
        batch_op.create_index('idx_user_state_snapshots__user__market_id__timestamp', ['user', 'marketId', 'timestamp'], unique=False)

    with op.batch_alter_table('user_states', schema=None) as batch_op:
        batch_op.create_index('idx_user_states__user__market_id__timestamp', ['user', 'marketId', 'timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_states', schema=None) as batch_op:
        batch_op.drop_index('idx_user_states__user__market_id__timestamp')

    with op.batch_alter_table('user_state_snapshots', schema=None) as batch_op:
        batch_op.drop_index('idx_user_state_snapshots__user__market_id__timestamp')

    with op.batch_alter_table('snapshot', schema=None) as batch_op:
        batch_op.drop_index('idx_snapshot__llamma__market_id__timestamp')

    # ### end Alembic commands ###
