repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: double-quote-string-fixer

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3.10
        args: [ --line-length=79 ]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        language_version: python3.10
        args: [ --max-line-length=79 ]
        stages: [ commit, push ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        language_version: python3.10
        stages: [ commit, push ]

  # Other Linters
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.27.0
    hooks:
      - id: yamllint
        args: [ "-d {extends: relaxed, rules: {line-length: {max: 120}}}" ]
        stages: [ commit, push ]

  - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: v0.1.0
    hooks:
      - id: dockerfilelint
        stages: [ commit, push ]
