from enum import Enum


OWNERSHIP = "OWNERSHIP"
PARAMETER = "PARAMETER"

DAY = 3600 * 24
WEEK = 3600 * 24 * 7
CRVUSD_CONTRACT = "0xf939e0a03fb07f59a73314e73794be0e57ac1b4e"


class PoolType(Enum):
    STABLE_FACTORY = "STABLE_FACTORY"
    CRYPTO_FACTORY = "CRYPTO_FACTORY"
    METAPOOL_FACTORY = "METAPOOL_FACTORY"
    REGISTRY_V1 = "REGISTRY_V1"
    REGISTRY_V2 = "REGISTRY_V2"
    LENDING = "LENDING"
    CRVUSD = "CRVUSD"
    TRICRYPTO_FACTORY = "TRICRYPTO_FACTORY"
